### ISSUE TITLE
 verifyStartStop(usage)

### ISSUE THREAD

**Issue by gantonel** [MasterMartbob/tplink-hs110-pump-monitor#1]
Hi MasterMartbob,

Congratulations!
Thanks for the code. I am getting multiple emails, because the logic in  verifyStartStop(usage) seems to be a bit convoluted. Either you or I should make sure it works as intended.

Maybe one should be able to decide how often to be sent emails, once idleThreshold is exceeded.

BTW Are there other commands  that we, could use? It would be great if one could retrieve the statistics as well.

Ideally, your code that produces email-alerts should be combined with the other project, namely jamesbarnett91/tplink-energy-monitor. What is the chance of that?

Regards

Giorgio

**Comment by mchenier** [comment]
I fix the probem with the power_mw. The problem was that Revision2.0 of HS110 is using power_mw but revision 1.0 use power. I made the change to support both.
You seem to have an other bug because for me I receive the email one time when it start and one time when it stop. So you are receiving a email every read is that it ? Show me your .env file but remove your email and password.

For the idle yes it is a problem I will fix that so it will be sent only one time or every x amount of time.

We could probably make our own stats and graph them tell me what you would like to see because the other project jamesbarnett91/tplink-energy-monitor was focusing on power consumption and that is not really a concern for me with the pump. So I won't try to merge those two project.

You could look at the api I'm using https://www.npmjs.com/package/tplink-cloud-api if you see other information you would like to leverage.

**Comment by mchenier** [comment]
There you can get latest code the fix for the idleThreshold is there.

**Comment by gantonel** [comment]
Hi MasterMartbob,

Thanks again.
I have not yet tried your newest version.

I know that the pump started during the night, but did not receive any emails.
The terminal window seems to show that the process terminated.

The terminal output includes the following "path: '/?appName=Kasa_Android&termID=aad6…”
I did not think the name Kasa_Android had anything to do with what I am running.
How did this intrude in my running process?
Should I be worried about that?
I have kept the whole file. The same output has appeared more than once.
Sometimes the normal process resumed, but after the last occurrence the process must have stopped totally, hence the next suggestion.

SUGGESTION: if we are going to print to screen the “usage” could we also have a timestamp next to each one?
Also I would find it more useful if the data was all on one line and comma separated.
Instead of {
  voltage_mv: 236513,
  current_ma: 18,
  power_mw: 0,
  total_wh: 28,
  err_code: 0
}
I would prefer {2020-03-29T11:24:53.240,voltage_mv: 236513,current_ma: 18,power_mw: 0,total_wh: 28,err_code: 0}




As far as receiving multiple email, that has stopped.

As far as the output on the log, we could record the total_wh at the end of each line as follows

[2020-03-29T11:24:53.240] [INFO] monitor - Pump Stopped, # 2, total_wh:28
The #2 in the example line above would be a nice addition to quickly detect how many emails one should have received!

You are correct, Any statistic information could be obtained from the logfile as long as the total_wh is recorded there on each line.
So, upon reflection, there is no real need to merge the two projects.

I hope you don’t mind me making such suggestions. I could implement them, but if possible it would be better to have bit of software that works well for both, rather than creating branches.

Regards

Giorgio Antonelli

**Comment by mchenier** [comment]
Yes I have the same problem that the process stop in the middle of the night. I will have to get more information on that before I can fix that.  For the log it should be simple to add your request but Im not sure of the use of adding the total_wh every time pump start or stop. If you want to amke the change I really don't mind just make a pull request afterward and I'll integrate it to the master branch.

**Comment by mchenier** [comment]
I did a modification for the log to be in one line and added the timestamp. I outputed every read in the log file as well so maybe I will have more information when it goes down.

**Comment by gantonel** [comment]
I think I now know why I have sometimes received multiple emails
I suspect I may have multiple apps running, because I may not have terminated one properly before starting another!
I will need to ensure that only one node is running at any one time.
